### ISSUE TITLE
Adding git tag

### ISSUE THREAD

**Issue by MasatoshiTada** [mercari/go-circuitbreaker#12]
Since this repository has no git tags, it is a little inconvenient when we use Go modules.
This repository should have tags like `v0.0.1`.
Thank you for your consideration.

**Comment by KarthikNayak** [comment]
Bumping this gently!

**Comment by nerocrux** [comment]
Sorry for the long wait. I created a release.
https://github.com/mercari/go-circuitbreaker/releases/tag/v0.0.1
